<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Portal\Module'                        => __DIR__ . '/Module.php',
    'Portal\Controller\IndexController' => __DIR__ . '/src/Portal/Controller/IndexController.php',
    'Portal\Framework\TestCase'        => __DIR__ . '/tests/Portal/Framework/TestCase.php',
    'Portal\SampleTest'                => __DIR__ . '/tests/Portal/SampleTest.php',
);