<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'Demo\Module'                     => __DIR__ . '/Module.php',
	'Demo\Controller\IndexController' => __DIR__ . '/src/Demo/Controller/IndexController.php',
	'Demo\Framework\TestCase'         => __DIR__ . '/tests/Demo/Framework/TestCase.php',
	'Demo\SampleTest'                 => __DIR__ . '/tests/Demo/SampleTest.php',
);