Nuevo Usuario



<div class="row">

<h1><?php echo $this->titulo?></h1>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.'/demo/usuario/recibe',
    'method' => 'post',
    'class' => 'vform label-right'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<fieldset class="c12">
<!-- forma1 de imprimir elementos de formulario -->
    <fieldset class="c6">
        <?php
            $name = $form->get('nombre');
            echo $formLabel->openTag().$name->getOption('label').$formLabel->closeTag();
            echo $this->formInput($name);
        ?>
    </fieldset>
    <!-- forma 2 : de imprimir elementos de formulario -->
    <fieldset class="c6">
        <?php   echo $this->formRow($form->get('apellido')) ?>
    </fieldset>

    <fieldset class="c6">
        <?php   echo $this->formRow($form->get('email')) ?>
    </fieldset>
     <fieldset class="c6">
        <?php   echo $this->formRow($form->get('pass')) ?>
    </fieldset>

<div class="clear"></div>

	<fieldset class=" text-right">
        <?php echo $this->formRow($form->get('btnEnviar')) ?>
		<?php echo $this->formRow($form->get('btnSend')) ?>
	</fieldset>

</fieldset>

<?php echo $this->form()->closeTag() ?>
</div>