ESTO ES UN FRM DE ZEND



<div class="row">

<h1><?php echo $this->titulo?></h1>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.'/demo/formulario/recibe',
    'method' => 'post',
    'class' => 'vform label-right'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<fieldset class="c12">
    <fieldset class="c6">
        <?php
            $name = $form->get('Nombre');
            echo $formLabel->openTag().$name->getOption('label').$formLabel->closeTag();
            echo $this->formInput($name);
        ?>
    </fieldset>

     <fieldset class="c6">
        <?php
            $name = $form->get('Nombre');
            echo $formLabel->openTag().$name->getOption('label').$formLabel->closeTag();
            echo $this->formInput($name);
        ?>
    </fieldset>

     <fieldset class="c6">
        <?php
            $name = $form->get('Nombre');
            echo $formLabel->openTag().$name->getOption('label').$formLabel->closeTag();
            echo $this->formInput($name);
        ?>
    </fieldset>

     <fieldset class="c6">
        <?php
            $name = $form->get('Nombre');
            echo $formLabel->openTag().$name->getOption('label').$formLabel->closeTag();
            echo $this->formInput($name);
        ?>
    </fieldset>


    <fieldset class="c6">
        <?php
            $email = $form->get('email');
            echo $formLabel->openTag().$email->getOption('label').$formLabel->closeTag();
            echo $this->formInput($email);
            //echo $this->formElementErrors($name);
        ?>
    </fieldset>

     <fieldset class="c6">
        <?php
            $apellidos = $form->get('Apellido');
            echo $formLabel->openTag().$apellidos->getOption('label').$formLabel->closeTag();
            echo $this->formInput($apellidos);
        ?>
    </fieldset>

    <fieldset class="c6">
        <?php
            $form_element = $form->get('emailUser');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formInput($form_element);
        ?>
    </fieldset>


    <fieldset class="c6">
        <?php
            $form_element = $form->get('mensaje');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formTextarea($form_element);
        ?>
    </fieldset>

 <fieldset class="c6">
        <?php
            $form_element = $form->get('Captcha');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formCaptcha($form_element);
        ?>
    </fieldset>





	<fieldset class=" text-right">
		<?php echo $this->formElement($form->get('send')) ?>
	</fieldset>
</fieldset>

<?php echo $this->form()->closeTag() ?>
</div>