ESTO ES UN FRM DE ZEND



<div class="row">

<h1><?php echo $this->titulo?></h1>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.'/demo/formulario/recibe',
    'method' => 'post',
    'class' => 'vform label-right'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<fieldset class="c12">
    <fieldset class="c6">
        <?php
            $name = $form->get('Nombre');
            echo $formLabel->openTag().$name->getOption('label').$formLabel->closeTag();
            echo $this->formInput($name);
        ?>
    </fieldset>
    <fieldset class="c6">
        <?php
            $apellidos = $form->get('Apellido');
            echo $formLabel->openTag().$apellidos->getOption('label').$formLabel->closeTag();
            echo $this->formInput($apellidos);
        ?>
    </fieldset>

    <fieldset class="c6">
        <?php
            $form_element = $form->get('emailUser');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formInput($form_element);
        ?>
    </fieldset>


    <fieldset class="c6">
        <?php
            $form_element = $form->get('mensaje');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formTextarea($form_element);
        ?>
    </fieldset>

 <fieldset class="c6">
        <?php
            $form_element = $form->get('Captcha');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formCaptcha($form_element);
        ?>
    </fieldset>


 <fieldset class="c6">
        <?php
            $form_element = $form->get('chk_politica');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formCheckbox($form_element);
        ?>
    </fieldset>

 <fieldset class="c6">
        <?php
            $form_element = $form->get('chk_multi');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formMultiCheckbox($form_element);
        ?>
    </fieldset>

    <fieldset class="c6">
        <?php
            $form_element = $form->get('rd_multi');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formRadio($form_element);
        ?>
    </fieldset>

    <fieldset class="c6">
        <?php
            $form_element = $form->get('Paises_');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formSelect($form_element);
        ?>
    </fieldset>

    <fieldset class="c6">
        <?php
            $form_element = $form->get('fechaNac');
            echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formDate($form_element);
        ?>
    </fieldset>

    <fieldset class="c6">
        <?php
            $form_element = $form->get('img_');
            // echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
             echo $this->formLabel($form_element);
            echo $this->formFile($form_element);
        ?>
    </fieldset>

    <fieldset class="c6">
        <?php
            $form_element = $form->get('img_');
            // echo $formLabel->openTag().$form_element->getOption('label').$formLabel->closeTag();
            echo $this->formLabel($form_element);
            echo $this->formFile($form_element);
        ?>
    </fieldset>

<p>form ROw </p>
     <fieldset class="c6">
        <?php
            echo $this->formRow($form->get('img_'));
        ?>
    </fieldset>

	<fieldset class=" text-right">
		<?php echo $this->formElement($form->get('btnEnviar')) ?>
	</fieldset>

</fieldset>

<?php echo $this->form()->closeTag() ?>
</div>