<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sistema\Module'                        => __DIR__ . '/Module.php',
    'Sistema\Controller\IndexController' => __DIR__ . '/src/Sistema/Controller/IndexController.php',
    'Sistema\Framework\TestCase'        => __DIR__ . '/tests/Sistema/Framework/TestCase.php',
    'Sistema\SampleTest'                => __DIR__ . '/tests/Sistema/SampleTest.php',
);